#!/bin/bash
set -euxo pipefail

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y docker.io curl jq
systemctl enable docker
systemctl start docker

mkdir -p /opt/sip-middleware/asterisk

if [[ ! -f /opt/sip-middleware/asterisk/modules.conf ]]; then
  docker rm -f sip-middleware-seed || true
  docker create --name sip-middleware-seed andrius/asterisk:latest >/dev/null
  docker cp sip-middleware-seed:/etc/asterisk/. /opt/sip-middleware/asterisk/
  docker rm -f sip-middleware-seed
fi

cat >/usr/local/bin/render-sip-middleware.sh <<'SCRIPT'
#!/bin/bash
set -euo pipefail

METADATA_BASE="http://metadata.google.internal/computeMetadata/v1/instance"
METADATA_HEADER="Metadata-Flavor: Google"
CONFIG_DIR="/opt/sip-middleware/asterisk"

get_meta() {
  local key="$1"
  curl -fsS -H "${METADATA_HEADER}" "${METADATA_BASE}/attributes/${key}" 2>/dev/null || true
}

PUBLIC_IP="$(curl -fsS -H "${METADATA_HEADER}" "${METADATA_BASE}/network-interfaces/0/access-configs/0/external-ip")"
TWILIO_TERMINATION_HOST="$(get_meta "twilio_termination_host")"
TWILIO_TERMINATION_PORT="$(get_meta "twilio_termination_port")"
TWILIO_USERNAME="$(get_meta "twilio_username")"
TWILIO_PASSWORD="$(get_meta "twilio_password")"
ELEVEN_ALLOW_CIDR="$(get_meta "eleven_allow_cidr")"
ELEVEN_USERNAME="$(get_meta "eleven_username")"
ELEVEN_PASSWORD="$(get_meta "eleven_password")"
ELEVEN_FORWARD_HOST="$(get_meta "eleven_forward_host")"
ELEVEN_FORWARD_PORT="$(get_meta "eleven_forward_port")"

if [[ -z "${TWILIO_TERMINATION_HOST}" ]]; then
  TWILIO_TERMINATION_HOST="replace-me.pstn.twilio.com"
fi
if [[ -z "${TWILIO_TERMINATION_PORT}" ]]; then
  TWILIO_TERMINATION_PORT="5060"
fi
if [[ -z "${ELEVEN_ALLOW_CIDR}" ]]; then
  ELEVEN_ALLOW_CIDR="127.0.0.1/32"
fi
if [[ -z "${ELEVEN_FORWARD_PORT}" ]]; then
  ELEVEN_FORWARD_PORT="5060"
fi

ELEVEN_INBOUND_AUTH_LINE=""
ELEVEN_AUTH_BLOCK=""
if [[ -n "${ELEVEN_USERNAME}" && -n "${ELEVEN_PASSWORD}" ]]; then
  ELEVEN_INBOUND_AUTH_LINE="auth=eleven-auth"
  ELEVEN_AUTH_BLOCK=$(cat <<AUTH
[eleven-auth]
type=auth
auth_type=userpass
username=${ELEVEN_USERNAME}
password=${ELEVEN_PASSWORD}
AUTH
)
fi

OUTBOUND_AUTH_LINE=""
AUTH_BLOCK=""
if [[ -n "${TWILIO_USERNAME}" && -n "${TWILIO_PASSWORD}" ]]; then
  OUTBOUND_AUTH_LINE="outbound_auth=twilio-auth"
  AUTH_BLOCK=$(cat <<AUTH
[twilio-auth]
type=auth
auth_type=userpass
username=${TWILIO_USERNAME}
password=${TWILIO_PASSWORD}
AUTH
)
fi

ELEVEN_FORWARD_PJSIP_BLOCK=""
FROM_TWILIO_DIALPLAN_BLOCK=$(cat <<'DIALPLAN'
[from-twilio]
exten => _X.,1,NoOp(Inbound from Twilio is not configured on this test middleware)
 same => n,Hangup(403)

exten => _+X.,1,NoOp(Inbound from Twilio is not configured on this test middleware)
 same => n,Hangup(403)

exten => s,1,NoOp(Inbound from Twilio default route)
 same => n,Hangup(403)
DIALPLAN
)

if [[ -n "${ELEVEN_FORWARD_HOST}" ]]; then
  ELEVEN_FORWARD_PJSIP_BLOCK=$(cat <<PJSIP
[eleven-forward-aor]
type=aor
contact=sip:${ELEVEN_FORWARD_HOST}:${ELEVEN_FORWARD_PORT}

[eleven-forward]
type=endpoint
transport=transport-udp
context=from-eleven
disallow=all
allow=ulaw,alaw,g722
allow_subscribe=no
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
aors=eleven-forward-aor
from_domain=${ELEVEN_FORWARD_HOST}
PJSIP
)

  FROM_TWILIO_DIALPLAN_BLOCK=$(cat <<'DIALPLAN'
[from-twilio]
exten => _+X.,1,NoOp(Forward +E164 call from Twilio to Eleven ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN}@eleven-forward,90)
 same => n,Hangup()

exten => _X.,1,NoOp(Forward numeric call from Twilio to Eleven ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN}@eleven-forward,90)
 same => n,Hangup()

exten => s,1,NoOp(Received INVITE from Twilio without a numeric user part)
 same => n,Hangup(404)
DIALPLAN
)
fi

cat >"${CONFIG_DIR}/pjsip.conf" <<EOF
; Auto-generated by render-sip-middleware.sh
[global]
type=global
user_agent=sip-middleware
endpoint_identifier_order=ip,username,anonymous

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060
external_signaling_address=${PUBLIC_IP}
external_media_address=${PUBLIC_IP}
local_net=10.0.0.0/8

[transport-tcp]
type=transport
protocol=tcp
bind=0.0.0.0:5060
external_signaling_address=${PUBLIC_IP}
external_media_address=${PUBLIC_IP}
local_net=10.0.0.0/8

[from-eleven-aor]
type=aor
max_contacts=20

[from-eleven]
type=endpoint
transport=transport-tcp
context=from-eleven
disallow=all
allow=ulaw,alaw,g722
allow_subscribe=no
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
aors=from-eleven-aor
${ELEVEN_INBOUND_AUTH_LINE}

[from-eleven-identify]
type=identify
endpoint=from-eleven
match=${ELEVEN_ALLOW_CIDR}

[twilio-trunk-aor]
type=aor
contact=sip:${TWILIO_TERMINATION_HOST}:${TWILIO_TERMINATION_PORT};transport=tcp

[twilio-trunk]
type=endpoint
transport=transport-tcp
context=from-twilio
disallow=all
allow=ulaw,alaw
allow_subscribe=no
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes
aors=twilio-trunk-aor
from_domain=${TWILIO_TERMINATION_HOST}
${OUTBOUND_AUTH_LINE}

${AUTH_BLOCK}

${ELEVEN_AUTH_BLOCK}

${ELEVEN_FORWARD_PJSIP_BLOCK}
EOF

cat >"${CONFIG_DIR}/extensions.conf" <<'EOF'
; Auto-generated by render-sip-middleware.sh
[general]
static=yes
writeprotect=no
clearglobalvars=no

[from-eleven]
exten => _+X.,1,NoOp(Forward +E164 call from Eleven to Twilio ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN}@twilio-trunk,90)
 same => n,Hangup()

exten => _X.,1,NoOp(Forward numeric call from Eleven to Twilio ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN}@twilio-trunk,90)
 same => n,Hangup()

exten => s,1,NoOp(Received INVITE without a numeric user part)
 same => n,Hangup(404)
EOF

printf "\n%s\n" "${FROM_TWILIO_DIALPLAN_BLOCK}" >>"${CONFIG_DIR}/extensions.conf"

cat >"${CONFIG_DIR}/rtp.conf" <<'EOF'
; Auto-generated by render-sip-middleware.sh
[general]
rtpstart=10000
rtpend=20000
strictrtp=no
icesupport=no
EOF
SCRIPT

chmod +x /usr/local/bin/render-sip-middleware.sh

cat >/etc/systemd/system/sip-middleware.service <<'UNIT'
[Unit]
Description=SIP middleware Asterisk container
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=-/usr/bin/docker rm -f sip-middleware
ExecStart=/usr/bin/docker run --detach --name sip-middleware --network host --restart unless-stopped --volume /opt/sip-middleware/asterisk:/etc/asterisk andrius/asterisk:latest
ExecStop=/usr/bin/docker stop sip-middleware
ExecStopPost=-/usr/bin/docker rm -f sip-middleware

[Install]
WantedBy=multi-user.target
UNIT

cat >/etc/systemd/system/sip-middleware-render.service <<'UNIT'
[Unit]
Description=Render SIP middleware config from metadata
After=network-online.target sip-middleware.service
Wants=network-online.target
Requires=sip-middleware.service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/render-sip-middleware.sh
ExecStartPost=/usr/bin/docker restart sip-middleware

[Install]
WantedBy=multi-user.target
UNIT

/usr/local/bin/render-sip-middleware.sh
systemctl daemon-reload
systemctl enable sip-middleware.service
systemctl start sip-middleware.service
systemctl enable sip-middleware-render.service
systemctl start sip-middleware-render.service
